#spring:
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#    open-in-view: true
#
#  sql:
#    init:
#      mode: always
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    hikari:
#      maximum-pool-size: 10
#      connection-timeout: 30000
#    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
#    username: ${PROD_DB_USERNAME}
#    password: ${PROD_DB_PASSWORD}
##    url: jdbc:postgresql://localhost:5433/test_intranet
##    username: postgres
##    password: peru2020
##
##server:
##  port: 3015
#logging:
#  level:
#    org.springframework: INFO
spring:
  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update